### PR TITLE
fix: copy prometheusexporter from otel collector contrib repo

### PR DESCRIPTION
**Pull request by tim-mwangi**
## Description
Since prometheusexporter turned on error logging in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8949/files the hypertrace collector logs fill up quite quickly since the various collectors reporting to it have different versions and so the local prometheus metrics registry is not able to handle the metrics differences and it ends up erroring out. The error logs are too verbose since all the failing metric attributes are logged as well. So in this solution we modify the logger to do nothing. We can be more fancy and have it log once every _n_ minutes.

### Testing
Tested locally. Prometheus unit tests still work.

### Checklist:
- [ ✅ ] My changes generate no new warnings

### CODE REVIEW

**Comment by tyroneyu** [comment]
Is there a way to track changes if the original otel collector contrib repo changes?  Or possibly log somewhere which commit/tag we copied from?

Is it this version?
```
replace github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.54.0 => ./exporter/prometheusexporter
```

However, that line in `go.mod` can be changed in future right?

**Review by tyroneyu — APPROVED** [review]

**Comment by tim-mwangi** [comment]
> Is there a way to track changes if the original otel collector contrib repo changes? Or possibly log somewhere which commit/tag we copied from?
> 
> Is it this version?
> 
> ```
> replace github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.54.0 => ./exporter/prometheusexporter
> ```
> 
> However, that line in `go.mod` can be changed in future right?

Yeah. Whoever is doing the otel collector upgrade takes care of it.

**Comment by tyroneyu** [comment]
> > Is there a way to track changes if the original otel collector contrib repo changes? Or possibly log somewhere which commit/tag we copied from?
> > Is it this version?
> > ```
> > replace github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.54.0 => ./exporter/prometheusexporter
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, that line in `go.mod` can be changed in future right?
> 
> Yeah. Whoever is doing the otel collector upgrade takes care of it.

If that line is changed in the future, we lose the knowledge that we copied over `0.54` of the prometheusexporter right?

So when prometheusexporter is updated, do we do a wholesale copy of that repo each time?

**Comment by tim-mwangi** [comment]
> > > Is there a way to track changes if the original otel collector contrib repo changes? Or possibly log somewhere which commit/tag we copied from?
> > > Is it this version?
> > > ```
> > > replace github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.54.0 => ./exporter/prometheusexporter
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > However, that line in `go.mod` can be changed in future right?
> > 
> > 
> > Yeah. Whoever is doing the otel collector upgrade takes care of it.
> 
> If that line is changed in the future, we lose the knowledge that we copied over `0.54` of the prometheusexporter right?
> 
> So when prometheusexporter is updated, do we do a wholesale copy of that repo each time?

Yes. There's a process to upgrade these copied-over modules.

**Pull request merged**
